name: CI

on:
  push:
    branches:
      - '**'   # Run CI on all branches

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run linter
        run: python -m flake8 .

      - name: Run tests
        run: pytest

      - name: Build Docker image
        run: |
          docker build -t karanmanola/flask-ml-api:${{ github.sha }} .
          docker tag karanmanola/flask-ml-api:${{ github.sha }} karanmanola/flask-ml-api:latest

      - name: Log in to DockerHub
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker images
        if: github.ref == 'refs/heads/main'
        run: |
          docker push karanmanola/flask-ml-api:${{ github.sha }}
          docker push karanmanola/flask-ml-api:latest